apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-stack-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: code
          name: head_hello
          label: 顶部欢迎代码
          value: "<h2>
👋Welcome To
      <strong style=color:#e99312>
        L1nSn0w's Blog
      </strong>
    </h2>"
          language: html
        - $formkit: text
          name: copy
          label: copyright
          value: "2020 - 2022 Jiewen's Blog"
        - $formkit: text
          name: icp
          label: 备案信息
          value: "京ICP备888888号-3"
    - group: leftSidebar
      label: 左边栏
      formSchema:
        - $formkit: text
          name: profileName
          label: 社交名称
          value: "Jiewen's Blog"
        - $formkit: text
          name: profileDesc
          label: 描述信息
          value: "无限进步.✍️"
        - $formkit: attachment
          name: profileAvatar
          label: 头像
          value: ""

        - $formkit: repeater
          name: socials
          id: socials
          key: socials
          label: 社交信息
          value: []
          children:
            - $formkit: select
              name: socials_select
              label: 平台
              options:
                - label: Github
                  value: github
                - label: Facebook
                  value: facebook
                - label: Twitter
                  value: twitter
                - label: Instagram
                  value: instagram
                - label: Telegram
                  value: telegram
                - label: Youtube
                  value: youtube
                - label: Bilibili
                  value: bilibili
                - label: 知乎
                  value: zhihu
                - label: QQ
                  value: qq
                - label: 微信公众号
                  value: wechat_group

            - $formkit: text
              name: socialUrl
              label: 链接
    - group: rightSidebar
      label: 右边栏
      formSchema:
        - $formkit: textarea
          name: indexWidgets
          label: 首页右组件
          value: "right-pic,search,archives,category,tags,newcomments"
          help: "目前提供的小部件有：right-pic（一张大图）, to-links（链接图片）, search（搜索）, category（文章分类）, tags（文章标签）， newcomments（最新评论） 。你可以随意组合或排序，以英文逗号隔开。"
        - $formkit: textarea
          name: postWidgets
          label: 文章右组件
          value: "right-pic,list,newcomments"
          help: "目前提供的小部件有：right-pic（一张大图）, to-links（链接图片）, search（搜索）, category（文章分类）, tags（文章标签）, list（文章目录）， newcomments（最新评论） 。你可以随意组合或排序，以英文逗号隔开。"
        - $formkit: textarea
          name: pageWidgets
          label: 自定义页面右组件
          value: "right-pic,list,newcomments"
          help: "目前提供的小部件有：right-pic（一张大图）, to-links（链接图片）, search（搜索）, category（文章分类）, tags（文章标签）, list（文章目录）， newcomments（最新评论） 。你可以随意组合或排序，以英文逗号隔开。"
        - $formkit: textarea
          name: linksWidgets
          label: 友情链接右组件
          value: "right-pic,list,newcomments"
          help: "目前提供的小部件有：right-pic（一张大图）, to-links（链接图片）, search（搜索）, category（文章分类）, tags（文章标签）, list（文章目录）， newcomments（最新评论） 。你可以随意组合或排序，以英文逗号隔开。"
        - $formkit: attachment
          name: rightPic
          label: Right-pic设置
          value: ""
        - $formkit: code
          name: toLinks
          label: To-links设置
          value: "<a href=https://travellings.link/ target=_blank rel=noopener title=开往-友链接力>
      <img src=https://travellings.link/assets/logo.gif alt=开往-友链接力 width=120>
    </a>
    <a href=https://www.foreverblog.cn/go.html target=_blank>
      <img src=https://img.foreverblog.cn/wormhole_1.gif alt style=width:auto;height:32px
           title=穿梭虫洞-随机访问十年之约友链博客>
    </a>"

    - group: article
      label: 文章页
      formSchema:
        - $formkit: select
          name: articleComment
          id: articleComment
          key: articleComment
          label: 评论使用模块
          value: halo-comment
          options:
            - label: 官方评论插件
              value: halo-comment
            - label: Waline评论插件
              value: waline-comment
        - $formkit: url
          if: "$get(articleComment).value === 'waline-comment'"
          name: walineUrl
          label: Waline服务地址
          value: ""
          help: "你的waline评论服务地址，具体参考：https://waline.js.org/"
        - $formkit: text
          if: "$get(articleComment).value === 'waline-comment'"
          name: walineAdmin
          label: Admin文字
          value: "👻屑博主"
          help: "管理者评论或回复时，名字旁边的介绍"


    - group: flinks
      label: 友链设置
      formSchema:
        - $formkit: attachment
          name: indexPhoto
          label: 顶部大图
          value: "/themes/theme-stack/assets/img/page.webp"
        - $formkit: text
          name: linksTitle
          label: 友链标题
          value: "『 Links 』友情链接"
        - $formkit: code
          name: linksInformation
          label: 我的信息
          value: "
          <p>
              名字： Jiewen’s Blog
            </p>
            <p>
              博客地址：https://www.jiewen.run
            </p>
            <p>
              简介：无限进步.🎈
            </p>
            "
        - $formkit: attachment
          name: myAvatar
          label: 头像
          value: "https://www.jiewen.run/upload/jiewen_icon.png"

          language: html
        - $formkit: code
          name: linksFormat
          label: 友链申请格式
          value: "<p>
              你的大名: XXXX
            </p>
            <p>
              你的简介: XXXXXX
            </p>
            <p>
              头像链接: XXXXXXX
            </p>
            <p>
              博客地址: XXXXXXXXXXXXXXXXXXX
            </p>"
          language: html
        - $formkit: code
          name: linksTip
          label: 其他信息
          value: "<p>
              正常安全的网址，尽量买一个好的域名。
            </p>
            <p>
              站点至少正常运行一个星期。
            </p>
            <p>
              只接受双向友链。
            </p>
            <p>
              头像链接稳定不掉。
            </p>
            <p>
              尽量不要接入广告
            </p>
            <p>
              尽量定期更新,如果长期不更新或者不维护的话我可能会将其撤掉!!!!! </p>"
          language: html