apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-stack-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: code
          name: head_hello
          label: 顶部欢迎代码
          value: "<h2>
👋Welcome To
      <strong style=color:#e99312>
        L1nSn0w's Blog
      </strong>
    </h2>"
          language: html
        - $formkit: text
          name: copy
          label: copyright
          value: "2020 - 2022 Jiewen's Blog"
        - $formkit: text
          name: icp
          label: 备案信息
          value: "京ICP备888888号-3"

    - group: leftSidebar
      label: 左边栏
      formSchema:
        - $formkit: text
          name: profileName
          label: 社交名称
          value: "Jiewen's Blog"
        - $formkit: text
          name: profileDesc
          label: 描述信息
          value: "无限进步.✍️"
        - $formkit: attachment
          name: profileAvatar
          label: 头像
          value: ""

        - $formkit: repeater
          name: socials
          id: socials
          key: socials
          label: 社交信息
          value: []
          children:
            - $formkit: select
              name: socials_select
              label: 平台
              options:
                - label: Github
                  value: github
                - label: Facebook
                  value: facebook
                - label: Twitter
                  value: twitter
                - label: Instagram
                  value: instagram
            - $formkit: text
              name: url
              label: 链接