apiVersion: theme.halo.run/v1alpha1
kind: Theme
spec:
  displayName: Theme Starter
  author:
    name: halo-dev
    website: 'https://halo.run'
  description: Halo 2.0 Theme base on Thymeleaf
  logo: 'https://halo.run/logo'
  website: 'https://halo.run'
  repo: 'https://github.com/halo-sigs/theme-starter'
  settingName: 
  configMapName:
  version: '1.0'
  require: '*'
metadata:
  name: theme-starter
